parameters:
  - name: artifact
    type: string
  # - name: py_versions
  #   type: object
  # - name: arch
  #   type: number

  - name: package_name
    type: string
steps:



  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: ${{parameters.artifact}}

  - script: "echo display: dir\ndir\necho display: $(Pipeline.Workspace)\ndir $(Pipeline.Workspace)\n"
    displayName: Display  artifact directories
  
  - script: |
      echo Displaying Python versions in $(Agent.ToolsDirectory)
      echo begin---------------------------
      dir $(Agent.ToolsDirectory)
      echo end-----------------------------
    displayName: Show python versions
    

  
  - bash: | 
      pip3 install -r requirements-dev.txt
      echo "--------" From: $(Pipeline.Workspace)
      dir $(Pipeline.Workspace)
      echo "--------" Install:  ${{ parameters.package_name }}

      python3 --version 
      pip3 --version
      pip3 install $(Pipeline.Workspace)/${{ parameters.package_name }}      --user --force-reinstall

      echo more explicitly 
      python3 -m pip install  $(Pipeline.Workspace)/${{ parameters.package_name }}      --user --force-reinstall
      python3 -m pip install  $(Pipeline.Workspace)/${{ parameters.package_name }}      --user --force-reinstall
      echo Use m version
      python3.6m -m pip install  $(Pipeline.Workspace)/${{ parameters.package_name }}      --user --force-reinstall
    displayName: Pip install



  - bash: |
        ports=(`nrf-device-lister -p PCA10056`)
        export PORT_A=${ports[0]}
        ports=(`nrf-device-lister -p PCA10040`)
        export PORT_B=${ports[0]}

        LOG_LEVEL="debug"
        DRV_LOG_LEVEL="info"
        
        set -e


        python3 tests/test_programming.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_ble_common_api.py     --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_rssi.py               --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_connection_update.py  --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_mtu.py                --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_passkey.py            --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_phy_update.py         --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_data_length.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python3 tests/test_server_client.py      --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}

    displayName: Jenkins run      
