parameters:
  - name: artifact_name
    type: string


  - name: package_name
    type: string

  - name: nodeVersion
    displayName: "Node version"
    type: string 
    default: 12.13.0

  - name: python_version
    displayName: "Python versions"
    type: string
    default: 3.6.8
      
  - name: arch
    type: number
    default: 64


  - name: python_name 
    type: string 
    default: \usr\bin\python3

steps:
  
#   
#    #Downlad a python artifact
#  - task: DownloadPipelineArtifact@2
#    inputs:
#      source: 'specific'
#      project: Wayland 
#      pipeline: 73
#      runVersion: 'specific'
#      runId: 10984
#      artifact: artifact-py-dependencies-macOSX
#      allowFailedBuilds: true
#

#  - task: DownloadPipelineArtifact@2
#    inputs:
#     source: current
#     artifact: ${{ parameters.artifact }}

  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific'
      project: Wayland 
      pipeline: 5
      runVersion: 'specific'
      runId: 10595
      artifact: ${{ parameters.artifact_name }}
      allowFailedBuilds: true




  - powershell: | 
          echo " Display .\ "
          dir .\
          echo "Display no keyword"
          dir
          echo "Display local artifacts"
          dir .\local_artifacts\
          echo "End display local_artifacts"
          echo "Last attempt at displaying"
          dir $(System.DefaultWorkingDirectory)/local_artifacts
          echo "End of last attempt"

          echo Displaying  $(Pipeline.Workspace)
          dir $(Pipeline.Workspace)

    failOnStderr: true 
    displayName: Display artifact directories


#
#  - task: UsePythonVersion@0
#    inputs:
#      versionSpec: ${{ parameters.python_version }}
#      architecture: x86
#    condition: eq( '${{ parameters.arch }}', 32) 
#
#  - task: UsePythonVersion@0
#    inputs:
#      versionSpec: ${{ parameters.python_version }}
#      architecture: x64
#    condition: eq( '${{ parameters.arch }}', 64) 
#
  - powershell: | 
      echo "--------" From: $(Pipeline.Workspace)
      dir $(Pipeline.Workspace)
      echo "Python ?"
      ${{ parameters.python_name }}  --version 
      ${{ parameters.python_name }}  -m pip --version 
      # echo "Python 3"
      # python3 --version 
      # python3 -m pip --version
      echo "--------" Install:  $(Pipeline.Workspace)/${{ parameters.artifact_name }}
    displayName: Show python versions

  # - powershell: |
  #     ${{ parameters.python_name }}  -m pip install --upgrade pip --user
  #     echo "start run python install artifact"
  #     ${{ parameters.python_name }}  -m pip uninstall  -y --quiet --quiet pc-ble-driver-py
  #       #      ${{ parameters.python_name }} -m pip install --user -r requirements-dev.txt
  #     ${{ parameters.python_name }}  -m pip install  --user --force-reinstall  $(Pipeline.Workspace)/${{ parameters.package_name }}
  #     echo "end python install artifact"
  #   condition: always()
  #   failOnStderr: true 
  #   displayName: Pip install
 
  - task: DownloadPipelineArtifact@2
    inputs:

      source: 'specific'
      project: 'Wayland internal'
      buildId: '11329' 
      # pipeline: 67
      pipeline: 'NordicPlayground.nrftc'
      artifact: 'nrftc-Darwin'
      path: $(System.ArtifactsDirectory)
    displayName: Download nrftc





  - powershell: |
        echo "Showing contents of System.ArtifactsDirectory"      
        ls $(System.ArtifactsDirectory)


        ls -l  $(System.ArtifactsDirectory)/nrftc 
        chmod +x $(System.ArtifactsDirectory)/nrftc 
        ls -l  $(System.ArtifactsDirectory)/nrftc 

        echo "Begin run help "
        $ports=$(System.ArtifactsDirectory)/nrftc --help
        $ports=$(System.ArtifactsDirectory)/nrftc devices --help
        $ports=$(System.ArtifactsDirectory)/nrftc devices list --help
        
        echo "End  run help "


        echo "Dry run" 
        $(System.ArtifactsDirectory)/nrftc devices  list -b PCA10056 



        $ports=$(System.ArtifactsDirectory)/nrftc devices list -b PCA10056 
        echo "Ports: $ports"
        $PORT_A= $ports | Select-Object -first 1 
        $ports=$(System.ArtifactsDirectory)/nrftc devices list -b PCA10040 
        echo "Ports: $ports"
        $PORT_B= $ports | Select-Object -first 1 
      
        echo "Port A: ${PORT_A}"
        echo "Port B: ${PORT_B}"

        $LOG_LEVEL="debug"
        $DRV_LOG_LEVEL="info"

        Get-ChildItem .\tests\test_*.py
            | Sort-Object Name
            | ForEach-object{
                echo "Running test: $_.Name"
                ${{ parameters.python_name }} $_.FullName --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
                if ( -not $? ){ # Exit if an error is thrown
                    throw $Error[0]
                }
            }

#        ${{ parameters.python_name }}   tests/test_programming.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_ble_common_api.py     --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_rssi.py               --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_connection_update.py  --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_mtu.py                --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_passkey.py            --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_phy_update.py         --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_data_length.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
#        ${{ parameters.python_name }}   tests/test_server_client.py      --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}

    displayName: Jenkins run      
