parameters:
  - name: artifact
    type: string
  - name: py_versions
    type: object
  - name: arch
    type: number

  - name: package_name
    type: string
steps:



  - task: DownloadPipelineArtifact@2
    inputs:
      source: current
      artifact: ${{parameters.artifact}}

  - script: "echo display: dir\ndir\necho display: $(Pipeline.Workspace)\ndir $(Pipeline.Workspace)\n"
    displayName: Download artifact
    

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(py_version)
      addToPath: true 
      architecture: "x$(arch)" 

  # add python version here  
  #pip install
  
  - bash: | 
      pip install -r requirements-dev.txt
      pip install $(Pipeline.Workspace)/$(parameters.package_name)

    displayName: Pip install



  - bash: |
        ports=(`nrf-device-lister -p PCA10056`)
        export PORT_A=${ports[0]}
        ports=(`nrf-device-lister -p PCA10040`)
        export PORT_B=${ports[0]}

        LOG_LEVEL="debug"
        DRV_LOG_LEVEL="info"
        
        set -e
        python${i} -m pip install --user --force-reinstall pc_ble_driver_py-*-cp${i/./}${SOABI}-manylinux2010_*.whl
        python${i} tests/test_programming.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_ble_common_api.py     --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_rssi.py               --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_connection_update.py  --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_mtu.py                --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_passkey.py            --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_phy_update.py         --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_data_length.py        --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}
        python${i} tests/test_server_client.py      --port-a ${PORT_A} --port-b ${PORT_B} --log-level ${LOG_LEVEL} --driver-log-level ${DRV_LOG_LEVEL}

    displayName: Jenkins run      
